AWSTemplateFormatVersion: '2010-09-09'
Description: S3Bcuket with expiration

# ------------------------------------------------------------ #
# Input Parameters
# ------------------------------------------------------------ #
Parameters:
  S3BucketName:
    Description: Type of this BacketName.
    Type: String

Resources:
# ------------------------------------------------------------ #
# S3
# ------------------------------------------------------------ #
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LifecycleConfiguration:
        Rules:
        - Id: LifeCycleRule
          Status: Enabled
          ExpirationInDays: 365

# ------------------------------------------------------------ #
# Output Parameters
# ------------------------------------------------------------ #
Outputs:
  S3BucketName:
    Value: !Ref S3Bucket